# Configurations of ${artifactId}.

# Default theme for this app.
theme : "org.wso2.carbon.uuf.common.default.theme"

# Session manager configuration for this app.
sessionManagement:
  factoryClassName: "org.wso2.carbon.uuf.api.auth.InMemorySessionManagerFactory"
  timeout: 600

# Authorizer for this app.
authorizer: null

# Menus in this app.
menus :
  - name: "main"
    items:
      - text: "Home"
        link: "#"
        icon: "fw-home"
        submenus:
          - text: "Items"
            link: ""

# Error pages for this app.
errorPages:
  404: "/foundation/error/404"
  default: "/foundation/error/default"

# Authenticator configuration.
authenticator:
  className: "org.wso2.carbon.uuf.auth.DummyAuth"
  loginUri: "/simple-auth/login"
  logoutUri: "/simple-auth/logout"

# Security related configurations for this app.
security:
  csrfIgnoreUris: []
  xssIgnoreUris: []
  responseHeaders:
     staticResources:
      "Content-Security-Policy": "default-src 'none'; script-src 'self' ssl.google-analytics.com;"
     pages:
      "X-Frame-Options": "DENY"
